call add_formulation("Oral solution","Oral solution");
call add_formulation("Dispersible tablet","Dispersible tablet");
call add_formulation("Blister tablet","Blister tablet");
call add_formulation("Ointment","Ointment");
call add_formulation("Cream","Cream");
call add_formulation("Solution for nebulization","Solution for nebulization");
call add_formulation("Inhaler","Inhaler");
call add_formulation("Injection","Injection");
call add_formulation("Powder for oral suspension","Powder for oral suspension");
call add_formulation("Powder for injection","Powder for injection");
call add_formulation("Oral suspension","Oral suspension");
call add_formulation("Packet","Packet");
call add_formulation("Soft tablet","Soft tablet");
call add_formulation("Eye drops","Eye drops");
call add_formulation("Solution for topical application","Solution for topical application");
call add_formulation("Bottle","Bottle");
call add_formulation("Ear drops","Ear drops");
call add_formulation("Bag for iv infusion","Bag for iv infusion");
call add_formulation("For injection","For injection");
call add_formulation("Oral syrup","Oral syrup");
call add_formulation("Tablet blister","Tablet blister");
call add_formulation("Syrup","Syrup");
call add_formulation("Powder+ solvent 1ml","Powder+ solvent 1ml");
call add_formulation("Powder+ solvent 0.5ml","Powder+ solvent 0.5ml");
call add_formulation("Sublingual","Sublingual");
call add_formulation("Oral solution, 240ml","Oral solution, 240ml");
call add_formulation("Jelly","Jelly");
call add_formulation("For injection (spinal)","For injection (spinal)");
call add_formulation("Pellets","Pellets");
call add_formulation("Vaginal suppository","Vaginal suppository");
call add_formulation("Slow release tablet","Slow release tablet");
call add_formulation("Dispersable tablet","Dispersable tablet");
call add_formulation("Oral tablet","Oral tablet");
call add_formulation("Lotion","Lotion");
call add_formulation("Base tablet","Base tablet");
call add_formulation("Solution","Solution");
call add_formulation("Powder + solvent","Powder + solvent");
call add_formulation("Oral inhaler","Oral inhaler");
call add_formulation("Solution for nebulisation","Solution for nebulisation");
call add_formulation("Gel","Gel");
call add_formulation("Eye ointment","Eye ointment");
call add_formulation("Skin ointment","Skin ointment");