call add_other_drugs("Abacavir (abc) 20mg/ml","Abacavir (abc) 20mg/ml","Oral solution");
call add_other_drugs("Abacavir (abc) 300mg","Abacavir (abc) 300mg","Tablet(s)");
call add_other_drugs("Abacavir (abc) 60mg","Abacavir (abc) 60mg","Dispersible tablet");
call add_other_drugs("Abacavir/lamivudine (abc/3tc) 120mg/60mg","Abacavir/lamivudine (abc/3tc) 120mg/60mg","Dispersible tablet");
call add_other_drugs("Abacavir/lamivudine (abc/3tc) 600mg/300mg","Abacavir/lamivudine (abc/3tc) 600mg/300mg","Blister tablet");
call add_other_drugs("Abacavir/lamivudine (abc/3tc) 60mg/30mg","Abacavir/lamivudine (abc/3tc) 60mg/30mg","Dispersible tablet");
call add_other_drugs("Abacavir/lamivudine/zidovudine (abc/3tc/azt) 300mg/150mg/300mg","Abacavir/lamivudine/zidovudine (abc/3tc/azt) 300mg/150mg/300mg","Tablet(s)");
call add_other_drugs("Abacavir/lamivudine/zidovudine (abc/3tc/azt) 60mg/30mg/60mg","Abacavir/lamivudine/zidovudine (abc/3tc/azt) 60mg/30mg/60mg","Tablet(s)");
call add_other_drugs("Acetazolamide 250mg","Acetazolamide 250mg","Tablet(s)");
call add_other_drugs("Acetylsalicylic acid 100mg","Acetylsalicylic acid 100mg","Tablet(s)");
call add_other_drugs("Acetylsalicylic acid 300mg","Acetylsalicylic acid 300mg","Tablet(s)");
call add_other_drugs("Acetylsalicylic acid 500mg","Acetylsalicylic acid 500mg","Tablet(s)");
call add_other_drugs("Aciclovir 200mg","Aciclovir 200mg","Tablet(s)");
call add_other_drugs("Aciclovir 3%","Aciclovir 3%","Ointment");
call add_other_drugs("Aciclovir 5%","Aciclovir 5%","Cream");
call add_other_drugs("Albendazole 200mg","Albendazole 200mg","Tablet(s)");
call add_other_drugs("Albendazole 400mg","Albendazole 400mg","Tablet(s)");
call add_other_drugs("Albuterol 0.5ml solution of 5% (2.5mg)","Albuterol 0.5ml solution of 5% (2.5mg)","Solution for nebulization");
call add_other_drugs("Albuterol oral inhaler, 90mcg/dose","Albuterol oral inhaler, 90mcg/dose","Inhaler");
call add_other_drugs("Allopurinol 100mg","Allopurinol 100mg","Tablet(s)");
call add_other_drugs("Aluminium hydroxide 500mg","Aluminium hydroxide 500mg","Tablet(s)");
call add_other_drugs("Amiloride 5mg","Amiloride 5mg","Tablet(s)");
call add_other_drugs("Aminophylline 100mg","Aminophylline 100mg","Tablet(s)");
call add_other_drugs("Aminophylline 250mg/10ml","Aminophylline 250mg/10ml","Injection");
call add_other_drugs("Amitriptyline hcl 25mg tablet","Amitriptyline hcl 25mg tablet","Tablet(s)");
call add_other_drugs("Amodiaquine hcl, equivalent to 200mg","Amodiaquine hcl, equivalent to 200mg","Tablet(s)");
call add_other_drugs("Amoxicillin 125mg/5ml, 100ml","Amoxicillin 125mg/5ml, 100ml","Powder for oral suspension");
call add_other_drugs("Amoxicillin 250mg","Amoxicillin 250mg","Tablet(s)");
call add_other_drugs("Amoxicillin 250mg/5ml, 100ml","Amoxicillin 250mg/5ml, 100ml","Powder for oral suspension");
call add_other_drugs("Amoxicillin 500mg","Amoxicillin 500mg","Tablet(s)");
call add_other_drugs("Amoxicillin 500mg + clavulanic acid 125mg","Amoxicillin 500mg + clavulanic acid 125mg","Tablet(s)");
call add_other_drugs("Amphotericin b, 50mg (10ml)","Amphotericin b, 50mg (10ml)","Powder for injection");
call add_other_drugs("Ampicillin 1 gram","Ampicillin 1 gram","Powder for injection");
call add_other_drugs("Ampicillin 250mg","Ampicillin 250mg","Tablet(s)");
call add_other_drugs("Ampicillin 500mg","Ampicillin 500mg","Powder for injection");
call add_other_drugs("Antacida (aluminium+magnesiumhydroxide) 300ml","Antacida (aluminium+magnesiumhydroxide) 300ml","Oral suspension");
call add_other_drugs("Anti-haemorrhoid 30g","Anti-haemorrhoid 30g","Ointment");
call add_other_drugs("Anti-haemorrhoid suppositories","Anti-haemorrhoid suppositories","Tablet(s)");
call add_other_drugs("Anti-rabies immunoglobuline, human 300iu/2ml","Anti-rabies immunoglobuline, human 300iu/2ml","Injection");
call add_other_drugs("Anti-snake bite serum, africa (10 snakes), 10ml","Anti-snake bite serum, africa (10 snakes), 10ml","Injection");
call add_other_drugs("Artemether 20mg + lumefantrine 120mg (coartem)","Artemether 20mg + lumefantrine 120mg (coartem)","Tablet(s)");
call add_other_drugs("Artemether 20mg/ml, 1ml","Artemether 20mg/ml, 1ml","Injection");
call add_other_drugs("Artemether 80mg/ml, 1ml","Artemether 80mg/ml, 1ml","Injection");
call add_other_drugs("Artesunate 100mg","Artesunate 100mg","Tablet(s)");
call add_other_drugs("Artesunate 50mg","Artesunate 50mg","Tablet(s)");
call add_other_drugs("Artesunate 50mg + amodiaquine 153mg","Artesunate 50mg + amodiaquine 153mg","Tablet(s)");
call add_other_drugs("Asunaprevir, 100mg","Asunaprevir, 100mg","Capsule");
call add_other_drugs("Atazanavir (atv) 150mg","Atazanavir (atv) 150mg","Tablet(s)");
call add_other_drugs("Atazanavir (atv) 200mg","Atazanavir (atv) 200mg","Tablet(s)");
call add_other_drugs("Atazanavir (atv) 300mg","Atazanavir (atv) 300mg","Tablet(s)");
call add_other_drugs("Atazanavir (atv) 50mg oral powder","Atazanavir (atv) 50mg oral powder","Packet");
call add_other_drugs("Atazanavir/ritonavir (atv/ rtv) 150mg/100mg","Atazanavir/ritonavir (atv/ rtv) 150mg/100mg","Soft tablet");
call add_other_drugs("Atazanavir/ritonavir (atv/ rtv) 200mg/100mg","Atazanavir/ritonavir (atv/ rtv) 200mg/100mg","Soft tablet");
call add_other_drugs("Atazanavir/ritonavir (atv/ rtv) 300mg/100mg","Atazanavir/ritonavir (atv/ rtv) 300mg/100mg","Soft tablet");
call add_other_drugs("Atazanavir/ritonavir (atv/ rtv) 50mg oral powder/ 100mg","Atazanavir/ritonavir (atv/ rtv) 50mg oral powder/ 100mg","Soft tablet");
call add_other_drugs("Atenolol 100mg","Atenolol 100mg","Tablet(s)");
call add_other_drugs("Atenolol 50mg","Atenolol 50mg","Tablet(s)");
call add_other_drugs("Atropine sulphate 1%, 5ml","Atropine sulphate 1%, 5ml","Eye drops");
call add_other_drugs("Atropine sulphate 1mg/ml, 1ml","Atropine sulphate 1mg/ml, 1ml","Injection");
call add_other_drugs("Azathioprine 50mg","Azathioprine 50mg","Tablet(s)");
call add_other_drugs("Azithromycine 200mg/5ml, 15ml","Azithromycine 200mg/5ml, 15ml","Oral suspension");
call add_other_drugs("Azithromycine 250 mg","Azithromycine 250 mg","Tablet(s)");
call add_other_drugs("Beclometasone oral inhaler, 50mcg/dose, 200 doses","Beclometasone oral inhaler, 50mcg/dose, 200 doses","Inhaler");
call add_other_drugs("Benzathine penicillin 1.2 miu","Benzathine penicillin 1.2 miu","Powder for injection");
call add_other_drugs("Benzathine penicillin 2.4 miu","Benzathine penicillin 2.4 miu","Powder for injection");
call add_other_drugs("Benzoic acid 6% + salicylic acid 3% ointment, 40g","Benzoic acid 6% + salicylic acid 3% ointment, 40g","Ointment");
call add_other_drugs("Benzoic acid 6% + salicylic acid 3% ointment, 800g","Benzoic acid 6% + salicylic acid 3% ointment, 800g","Ointment");
call add_other_drugs("Benzotropine 1mg","Benzotropine 1mg","Tablet(s)");
call add_other_drugs("Benzylbenzoate 25% application, 1 liter","Benzylbenzoate 25% application, 1 liter","Solution for topical application");
call add_other_drugs("Benzylbenzoate 90% saponated, 1 liter","Benzylbenzoate 90% saponated, 1 liter","Solution for topical application");
call add_other_drugs("Benzylpenicillin 1 miu","Benzylpenicillin 1 miu","Powder for injection");
call add_other_drugs("Benzylpenicillin 5 miu","Benzylpenicillin 5 miu","Powder for injection");
call add_other_drugs("Betamethasone 0.1%, 15g","Betamethasone 0.1%, 15g","Cream");
call add_other_drugs("Biperiden hcl 2mg","Biperiden hcl 2mg","Tablet(s)");
call add_other_drugs("Bisacodyl 5mg","Bisacodyl 5mg","Tablet(s)");
call add_other_drugs("Bleomycin, 15.000 iu","Bleomycin, 15.000 iu","Powder for injection");
call add_other_drugs("Bupivacaine 0.5%, 20ml","Bupivacaine 0.5%, 20ml","Injection");
call add_other_drugs("Bupivacaine spinal heavy 0.5%, 4ml","Bupivacaine spinal heavy 0.5%, 4ml","Injection");
call add_other_drugs("Calamine, 500ml","Calamine, 500ml","Cream");
call add_other_drugs("Calcium gluconate 1g/10ml (2.23mmol)","Calcium gluconate 1g/10ml (2.23mmol)","Injection");
call add_other_drugs("Calcium lactate 300mg","Calcium lactate 300mg","Tablet(s)");
call add_other_drugs("Captopril 25mg","Captopril 25mg","Tablet(s)");
call add_other_drugs("Carbamazepine 200mg","Carbamazepine 200mg","Tablet(s)");
call add_other_drugs("Carbimazole 5mg","Carbimazole 5mg","Tablet(s)");
call add_other_drugs("Carbon absorbent 125mg","Carbon absorbent 125mg","Bottle");
call add_other_drugs("Cefalexin 500mg","Cefalexin 500mg","Tablet(s)");
call add_other_drugs("Cefixime 200 mg","Cefixime 200 mg","Tablet(s)");
call add_other_drugs("Cefixime 400 mg","Cefixime 400 mg","Tablet(s)");
call add_other_drugs("Ceftriaxone 1g","Ceftriaxone 1g","Powder for injection");
call add_other_drugs("Ceftriaxone 250mg","Ceftriaxone 250mg","Powder for injection");
call add_other_drugs("Ceftriaxone 500mg","Ceftriaxone 500mg","Powder for injection");
call add_other_drugs("Chloramphenicol 0.5%, eye drops, 10ml","Chloramphenicol 0.5%, eye drops, 10ml","Eye drops");
call add_other_drugs("Chloramphenicol 1% eye, 5g tubes","Chloramphenicol 1% eye, 5g tubes","Ointment");
call add_other_drugs("Chloramphenicol 10% ear drops, 10ml","Chloramphenicol 10% ear drops, 10ml","Ear drops");
call add_other_drugs("Chloramphenicol 125mg/5ml, 100ml","Chloramphenicol 125mg/5ml, 100ml","Oral suspension");
call add_other_drugs("Chloramphenicol 1g","Chloramphenicol 1g","Injection");
call add_other_drugs("Chloramphenicol 250mg","Chloramphenicol 250mg","Tablet(s)");
call add_other_drugs("Chloramphenicol 500mg/2ml in oil","Chloramphenicol 500mg/2ml in oil","Injection");
call add_other_drugs("Chloroquine phosphate 100mg","Chloroquine phosphate 100mg","Tablet(s)");
call add_other_drugs("Chloroquine phosphate 10mg base/ml, 60ml","Chloroquine phosphate 10mg base/ml, 60ml","Oral solution");
call add_other_drugs("Chloroquine phosphate 150mg","Chloroquine phosphate 150mg","Tablet(s)");
call add_other_drugs("Chloroquine phosphate 200mg base/5ml","Chloroquine phosphate 200mg base/5ml","Injection");
call add_other_drugs("Chlorphenamine maleate 10mg/ml, 1ml","Chlorphenamine maleate 10mg/ml, 1ml","Injection");
call add_other_drugs("Chlorphenamine maleate 4mg","Chlorphenamine maleate 4mg","Tablet(s)");
call add_other_drugs("Chlorpromazine hcl 100mg","Chlorpromazine hcl 100mg","Tablet(s)");
call add_other_drugs("Chlorpromazine hcl 25mg","Chlorpromazine hcl 25mg","Tablet(s)");
call add_other_drugs("Chlorpromazine hcl 50mg/2ml","Chlorpromazine hcl 50mg/2ml","Injection");
call add_other_drugs("Cimetidine 200mg","Cimetidine 200mg","Tablet(s)");
call add_other_drugs("Cimetidine 200mg/2ml","Cimetidine 200mg/2ml","Injection");
call add_other_drugs("Ciprofloxacin 250mg","Ciprofloxacin 250mg","Tablet(s)");
call add_other_drugs("Ciprofloxacin 500mg","Ciprofloxacin 500mg","Tablet(s)");
call add_other_drugs("Clotrimazole 1%, 20g tubes","Clotrimazole 1%, 20g tubes","Cream");
call add_other_drugs("Clotrimazole vaginal 500mg","Clotrimazole vaginal 500mg","Cream");
call add_other_drugs("Cloxacillin 125mg/5ml, 100ml","Cloxacillin 125mg/5ml, 100ml","Powder for oral suspension");
call add_other_drugs("Cloxacillin 250mg","Cloxacillin 250mg","Tablet(s)");
call add_other_drugs("Cloxacillin 500mg","Cloxacillin 500mg","Tablet(s)");
call add_other_drugs("Co-trimoxazole 100mg+20mg","Co-trimoxazole 100mg+20mg","Tablet(s)");
call add_other_drugs("Co-trimoxazole 200mg+40mg/5ml, 100ml","Co-trimoxazole 200mg+40mg/5ml, 100ml","Powder for oral suspension");
call add_other_drugs("Co-trimoxazole 400mg+80mg","Co-trimoxazole 400mg+80mg","Tablet(s)");
call add_other_drugs("Co-trimoxazole 800mg+160mg","Co-trimoxazole 800mg+160mg","Tablet(s)");
call add_other_drugs("Codeine phosphate 30mg","Codeine phosphate 30mg","Tablet(s)");
call add_other_drugs("Daclatasvir dihydrochloride (dcv), eq. 30 mg","Daclatasvir dihydrochloride (dcv), eq. 30 mg","Tablet(s)");
call add_other_drugs("Daclatasvir dihydrochloride (dcv), eq. 60 mg","Daclatasvir dihydrochloride (dcv), eq. 60 mg","Tablet(s)");
call add_other_drugs("Dapsone 100mg","Dapsone 100mg","Tablet(s)");
call add_other_drugs("Darunavir (drv) 100mg/ml","Darunavir (drv) 100mg/ml","Oral suspension");
call add_other_drugs("Darunavir (drv) 150mg","Darunavir (drv) 150mg","Tablet(s)");
call add_other_drugs("Darunavir (drv) 300mg","Darunavir (drv) 300mg","Tablet(s)");
call add_other_drugs("Darunavir (drv) 400mg","Darunavir (drv) 400mg","Tablet(s)");
call add_other_drugs("Darunavir (drv) 600mg","Darunavir (drv) 600mg","Tablet(s)");
call add_other_drugs("Darunavir (drv) 600mg tablet + ritonavir (rtv) 80mg/ml oral solution","Darunavir (drv) 600mg tablet + ritonavir (rtv) 80mg/ml oral solution","Tablet(s)");
call add_other_drugs("Darunavir (drv) 75mg","Darunavir (drv) 75mg","Tablet(s)");
call add_other_drugs("Darunavir (drv) 75mg tablet","Darunavir (drv) 75mg tablet","Tablet(s)");
call add_other_drugs("Darunavir (drv) 800mg","Darunavir (drv) 800mg","Tablet(s)");
call add_other_drugs("Darunavir (drv) 800mg tablet + ritonavir (rtv)  80mg/ml oral solution","Darunavir (drv) 800mg tablet + ritonavir (rtv)  80mg/ml oral solution","Tablet(s)");
call add_other_drugs("Darunavir/ritonavir (drv/rtv)  100mg/ml oral suspension/ 100mg soft tablet","Darunavir/ritonavir (drv/rtv)  100mg/ml oral suspension/ 100mg soft tablet","Tablet(s)");
call add_other_drugs("Darunavir/ritonavir (drv/rtv) 100mg/ml oral suspension/ 100mg tablet","Darunavir/ritonavir (drv/rtv) 100mg/ml oral suspension/ 100mg tablet","Tablet(s)");
call add_other_drugs("Darunavir/ritonavir (drv/rtv) 100mg/ml oral suspension/ 80mg/ml oral solution","Darunavir/ritonavir (drv/rtv) 100mg/ml oral suspension/ 80mg/ml oral solution","Tablet(s)");
call add_other_drugs("Darunavir/ritonavir (drv/rtv) 150mg/100mg","Darunavir/ritonavir (drv/rtv) 150mg/100mg","Soft tablet");
call add_other_drugs("Darunavir/ritonavir (drv/rtv) 600mg/100mg","Darunavir/ritonavir (drv/rtv) 600mg/100mg","Soft tablet");
call add_other_drugs("Darunavir/ritonavir (drv/rtv) 75mg/100mg","Darunavir/ritonavir (drv/rtv) 75mg/100mg","Soft tablet");
call add_other_drugs("Darunavir/ritonavir (drv/rtv) 800mg/100mg","Darunavir/ritonavir (drv/rtv) 800mg/100mg","Tablet(s)");
call add_other_drugs("Dasabuvir 250mg","Dasabuvir 250mg","Tablet(s)");
call add_other_drugs("Dexamethasone 0.5mg","Dexamethasone 0.5mg","Tablet(s)");
call add_other_drugs("Dexamethasone 1mg/ml (as sodium phosphate), eye drops, 10ml","Dexamethasone 1mg/ml (as sodium phosphate), eye drops, 10ml","Eye drops");
call add_other_drugs("Dexamethasone sodium phosphate 5mg/ml, 1ml","Dexamethasone sodium phosphate 5mg/ml, 1ml","Injection");
call add_other_drugs("Dextrose 10% in water, 500ml bag","Dextrose 10% in water, 500ml bag","Bag for iv infusion");
call add_other_drugs("Dextrose 2.5% in nacl 0.45%, 1000ml bag","Dextrose 2.5% in nacl 0.45%, 1000ml bag","Bag for iv infusion");
call add_other_drugs("Dextrose 5% in water, 1000ml bag","Dextrose 5% in water, 1000ml bag","Bag for iv infusion");
call add_other_drugs("Dextrose 5% in water, 500ml bag","Dextrose 5% in water, 500ml bag","Bag for iv infusion");
call add_other_drugs("Dextrose 50%, 50ml","Dextrose 50%, 50ml","For injection");
call add_other_drugs("Diazepam 10mg/2ml","Diazepam 10mg/2ml","For injection");
call add_other_drugs("Diazepam 5mg","Diazepam 5mg","Tablet(s)");
call add_other_drugs("Diclofenac sodium 25mg","Diclofenac sodium 25mg","Tablet(s)");
call add_other_drugs("Diclofenac sodium 75mg/3ml","Diclofenac sodium 75mg/3ml","For injection");
call add_other_drugs("Didanosine (ddi) 125mg","Didanosine (ddi) 125mg","Tablet(s)");
call add_other_drugs("Didanosine (ddi) 200mg","Didanosine (ddi) 200mg","Tablet(s)");
call add_other_drugs("Didanosine (ddi) 250mg","Didanosine (ddi) 250mg","Tablet(s)");
call add_other_drugs("Didanosine (ddi) 2g oral powder, 4oz","Didanosine (ddi) 2g oral powder, 4oz","Powder for oral suspension");
call add_other_drugs("Didanosine (ddi) 400mg","Didanosine (ddi) 400mg","Tablet(s)");
call add_other_drugs("Didanosine (ddi) 4g oral powder, 8oz","Didanosine (ddi) 4g oral powder, 8oz","Powder for oral suspension");
call add_other_drugs("Digoxine 0.25mg","Digoxine 0.25mg","Tablet(s)");
call add_other_drugs("Digoxine 0.5mg/2ml","Digoxine 0.5mg/2ml","Injection");
call add_other_drugs("Dimenhydrinate 50 mg","Dimenhydrinate 50 mg","Tablet(s)");
call add_other_drugs("Diphenhydramine 25mg","Diphenhydramine 25mg","Tablet(s)");
call add_other_drugs("Dolutegravir (dtg) 10mg","Dolutegravir (dtg) 10mg","Tablet(s)");
call add_other_drugs("Dolutegravir (dtg) 25mg","Dolutegravir (dtg) 25mg","Tablet(s)");
call add_other_drugs("Dolutegravir (dtg) 50mg","Dolutegravir (dtg) 50mg","Tablet(s)");
call add_other_drugs("Dopamine hcl 200mg/5ml","Dopamine hcl 200mg/5ml","Injection");
call add_other_drugs("Doxycycline 100mg","Doxycycline 100mg","Tablet(s)");
call add_other_drugs("Efavirenz (efv) 200mg","Efavirenz (efv) 200mg","Capsule");
call add_other_drugs("Efavirenz (efv) 50mg","Efavirenz (efv) 50mg","Capsule");
call add_other_drugs("Efavirenz (efv) 600mg","Efavirenz (efv) 600mg","Tablet(s)");
call add_other_drugs("Elbasvir 50mg/grazoprevir 100mg","Elbasvir 50mg/grazoprevir 100mg","Tablet(s)");
call add_other_drugs("Emtricitabine (ftc) 10mg/ml oral solution, 170ml","Emtricitabine (ftc) 10mg/ml oral solution, 170ml","Oral solution");
call add_other_drugs("Emtricitabine (ftc) 200mg","Emtricitabine (ftc) 200mg","Tablet(s)");
call add_other_drugs("Entecavir   0.05 mg/ ml","Entecavir   0.05 mg/ ml","Oral syrup");
call add_other_drugs("Entecavir  0.5 mg","Entecavir  0.5 mg","Tablet(s)");
call add_other_drugs("Entecavir  1 mg","Entecavir  1 mg","Tablet(s)");
call add_other_drugs("Ephedrine hcl 30mg/ml, 1ml","Ephedrine hcl 30mg/ml, 1ml","Injection");
call add_other_drugs("Epinephrine 1mg/ml, 1ml (adrenaline)","Epinephrine 1mg/ml, 1ml (adrenaline)","Injection");
call add_other_drugs("Ergometrine maleate 0.5mg/ml, 1ml","Ergometrine maleate 0.5mg/ml, 1ml","Injection");
call add_other_drugs("Ergotamine 1mg + caffeine 100 mg","Ergotamine 1mg + caffeine 100 mg","Tablet(s)");
call add_other_drugs("Erythromycin 125mg/5ml, oral powder, 100ml","Erythromycin 125mg/5ml, oral powder, 100ml","Powder for oral suspension");
call add_other_drugs("Erythromycin 250mg","Erythromycin 250mg","Tablet(s)");
call add_other_drugs("Ethinylestradiol/levonorgestrel 0.03/0.15mg, 28","Ethinylestradiol/levonorgestrel 0.03/0.15mg, 28","Tablet blister");
call add_other_drugs("Etravirine (etr) 100mg","Etravirine (etr) 100mg","Tablet(s)");
call add_other_drugs("Etravirine (etr) 200mg","Etravirine (etr) 200mg","Tablet(s)");
call add_other_drugs("Etravirine (etr) 25mg","Etravirine (etr) 25mg","Tablet(s)");
call add_other_drugs("Fentanyl 0.1mg/2ml","Fentanyl 0.1mg/2ml","Injection");
call add_other_drugs("Ferrous fumarate 100mg/5ml oral suspension, 5 liter","Ferrous fumarate 100mg/5ml oral suspension, 5 liter","Oral suspension");
call add_other_drugs("Ferrous sulphate 200mg + folic acid 0.25mg","Ferrous sulphate 200mg + folic acid 0.25mg","Tablet(s)");
call add_other_drugs("Ferrous sulphate 200mg + folic acid 0.4mg","Ferrous sulphate 200mg + folic acid 0.4mg","Tablet(s)");
call add_other_drugs("Ferrous sulphate 200mg, coated tablet (65mg iron)","Ferrous sulphate 200mg, coated tablet (65mg iron)","Tablet(s)");
call add_other_drugs("Fluconazole 150mg","Fluconazole 150mg","Tablet(s)");
call add_other_drugs("Fluconazole 200mg","Fluconazole 200mg","Tablet(s)");
call add_other_drugs("Fluconazole 50mg","Fluconazole 50mg","Tablet(s)");
call add_other_drugs("Fluoxetine 20mg","Fluoxetine 20mg","Tablet(s)");
call add_other_drugs("Folic acid 5mg","Folic acid 5mg","Tablet(s)");
call add_other_drugs("Furosemide 20mg/2ml","Furosemide 20mg/2ml","Injection");
call add_other_drugs("Furosemide 40mg","Furosemide 40mg","Tablet(s)");
call add_other_drugs("Ganciclovir 500 mg","Ganciclovir 500 mg","Powder for injection");
call add_other_drugs("Gentamicin 0.3% eye drops, 5ml","Gentamicin 0.3% eye drops, 5ml","Eye drops");
call add_other_drugs("Gentamicin 20mg/2ml","Gentamicin 20mg/2ml","Injection");
call add_other_drugs("Gentamicin 80mg/2ml","Gentamicin 80mg/2ml","Injection");
call add_other_drugs("Glibenclamide 5mg","Glibenclamide 5mg","Tablet(s)");
call add_other_drugs("Griseofulvin 125mg","Griseofulvin 125mg","Tablet(s)");
call add_other_drugs("Griseofulvin 500mg","Griseofulvin 500mg","Tablet(s)");
call add_other_drugs("Haloperidol 5mg","Haloperidol 5mg","Tablet(s)");
call add_other_drugs("Haloperidol 5mg/ml, 1ml","Haloperidol 5mg/ml, 1ml","Injection");
call add_other_drugs("Heparine sodium 5000 iu/ml, 5ml","Heparine sodium 5000 iu/ml, 5ml","Injection");
call add_other_drugs("Hydralazine 20mg","Hydralazine 20mg","Powder for injection");
call add_other_drugs("Hydralazine hcl 25mg","Hydralazine hcl 25mg","Tablet(s)");
call add_other_drugs("Hydrochlorothiazide 25mg","Hydrochlorothiazide 25mg","Tablet(s)");
call add_other_drugs("Hydrochlorothiazide 50mg","Hydrochlorothiazide 50mg","Powder for injection");
call add_other_drugs("Hydrocortisone 100mg (as sodium succinate)","Hydrocortisone 100mg (as sodium succinate)","Powder for injection");
call add_other_drugs("Hydrocortisone acetate 1% cream, 15g","Hydrocortisone acetate 1% cream, 15g","Cream");
call add_other_drugs("Hydrocortisone acetate 1% eye ointment, 5g","Hydrocortisone acetate 1% eye ointment, 5g","Ointment");
call add_other_drugs("Hydrocortisone acetate 1% skin ointment, 15g","Hydrocortisone acetate 1% skin ointment, 15g","Ointment");
call add_other_drugs("Hyoscine butylbromide 10mg","Hyoscine butylbromide 10mg","Tablet(s)");
call add_other_drugs("Hyoscine butylbromide 20mg/ml, 1ml","Hyoscine butylbromide 20mg/ml, 1ml","Injection");
call add_other_drugs("Ibuprofen 200mg","Ibuprofen 200mg","Tablet(s)");
call add_other_drugs("Ibuprofen 400mg","Ibuprofen 400mg","Tablet(s)");
call add_other_drugs("Indometacin 25mg","Indometacin 25mg","Tablet(s)");
call add_other_drugs("Interferon pegylated alpha 2a, 135µg/0.5ml","Interferon pegylated alpha 2a, 135µg/0.5ml","Syrup");
call add_other_drugs("Interferon pegylated alpha 2a, 180 µg, powder+ solvent 1ml","Interferon pegylated alpha 2a, 180 µg, powder+ solvent 1ml","Powder+ solvent 1ml");
call add_other_drugs("Interferon pegylated alpha 2a,, 180µg/0.5ml, syrup","Interferon pegylated alpha 2a,, 180µg/0.5ml, syrup","Syrup");
call add_other_drugs("Interferon pegylated alpha 2b, 120 µg, powder+ solvent 0.5ml","Interferon pegylated alpha 2b, 120 µg, powder+ solvent 0.5ml","Powder+ solvent 0.5ml");
call add_other_drugs("Interferon pegylated alpha 2b, 80 µg, powder+ solvent 0.5ml","Interferon pegylated alpha 2b, 80 µg, powder+ solvent 0.5ml","Powder+ solvent 0.5ml");
call add_other_drugs("Iron dextran 100mg/2ml","Iron dextran 100mg/2ml","Injection");
call add_other_drugs("Isosorbide dinitrate 5mg","Isosorbide dinitrate 5mg","Sublingual");
call add_other_drugs("Ketamine 50mg/ml, 10ml","Ketamine 50mg/ml, 10ml","For injection");
call add_other_drugs("Ketoconazole 200mg","Ketoconazole 200mg","Tablet(s)");
call add_other_drugs("Lamivudine (3tc) 10mg/ml oral solution, 240ml","Lamivudine (3tc) 10mg/ml oral solution, 240ml","Oral solution, 240ml");
call add_other_drugs("Lamivudine (3tc) 150mg","Lamivudine (3tc) 150mg","Tablet(s)");
call add_other_drugs("Lamivudine (3tc) 300mg","Lamivudine (3tc) 300mg","Tablet(s)");
call add_other_drugs("Lamivudine (3tc) 50mg/5ml","Lamivudine (3tc) 50mg/5ml","Bottle");
call add_other_drugs("Ledipasvir 90 mg / sofosbuvir 400 mg","Ledipasvir 90 mg / sofosbuvir 400 mg","Tablet(s)");
call add_other_drugs("Levodopa/carbidopa 100mg/25mg","Levodopa/carbidopa 100mg/25mg","Tablet(s)");
call add_other_drugs("Levodopa/carbidopa 250mg/25mg","Levodopa/carbidopa 250mg/25mg","Tablet(s)");
call add_other_drugs("Levonorgestrel 0.75mg","Levonorgestrel 0.75mg","Tablet(s)");
call add_other_drugs("Levothyroxine sodium 0.1mg","Levothyroxine sodium 0.1mg","Tablet(s)");
call add_other_drugs("Lidocaine hcl 1%, 20ml","Lidocaine hcl 1%, 20ml","Injection");
call add_other_drugs("Lidocaine hcl 2% + epinephrine dental, 1.8ml","Lidocaine hcl 2% + epinephrine dental, 1.8ml","Injection");
call add_other_drugs("Lidocaine hcl 2% jelly, 30ml","Lidocaine hcl 2% jelly, 30ml","Jelly");
call add_other_drugs("Lidocaine hcl 2%, 20ml","Lidocaine hcl 2%, 20ml","Injection");
call add_other_drugs("Lidocaine hcl 5% + dextrose 7.5%, 2ml","Lidocaine hcl 5% + dextrose 7.5%, 2ml","For injection (spinal)");
call add_other_drugs("Lisinopril 10mg","Lisinopril 10mg","Tablet(s)");
call add_other_drugs("Lisinopril 5mg","Lisinopril 5mg","Tablet(s)");
call add_other_drugs("Loperamide hcl 2mg","Loperamide hcl 2mg","Tablet(s)");
call add_other_drugs("Lopinavir/ritonavir (lpv/ rtv) 200mg/50mg","Lopinavir/ritonavir (lpv/ rtv) 200mg/50mg","Tablet(s)");
call add_other_drugs("Lopinavir/ritonavir (lpv/ rtv) 80mg/ml / 20mg/ml","Lopinavir/ritonavir (lpv/ rtv) 80mg/ml / 20mg/ml","Oral solution");
call add_other_drugs("Lopinavir/ritonavir (lpv/ rtv)100mg/25mg","Lopinavir/ritonavir (lpv/ rtv)100mg/25mg","Tablet(s)");
call add_other_drugs("Lopinavir/ritonavir (lpv/rtv) 40mg/10mg","Lopinavir/ritonavir (lpv/rtv) 40mg/10mg","Capsule");
call add_other_drugs("Lorazepam 0.5mg","Lorazepam 0.5mg","Tablet(s)");
call add_other_drugs("Lorazepam 1mg","Lorazepam 1mg","Tablet(s)");
call add_other_drugs("Magnesium sulphate 50%, 20ml","Magnesium sulphate 50%, 20ml","Injection");
call add_other_drugs("Magnesium/trisilicate 250/120 mg","Magnesium/trisilicate 250/120 mg","Tablet(s)");
call add_other_drugs("Mannitol 20% solution, 500ml","Mannitol 20% solution, 500ml","Bag for iv infusion");
call add_other_drugs("Mebendazole 100mg","Mebendazole 100mg","Tablet(s)");
call add_other_drugs("Mebendazole 100mg/5ml oral suspension, 100ml","Mebendazole 100mg/5ml oral suspension, 100ml","Oral suspension");
call add_other_drugs("Mebendazole 500mg","Mebendazole 500mg","Tablet(s)");
call add_other_drugs("Meclazine 25mg","Meclazine 25mg","Tablet(s)");
call add_other_drugs("Medroxyprogesteronacetate 150mg/ml, 1ml","Medroxyprogesteronacetate 150mg/ml, 1ml","Injection");
call add_other_drugs("Mefloquine 250mg","Mefloquine 250mg","Tablet(s)");
call add_other_drugs("Metformine hcl 500mg","Metformine hcl 500mg","Tablet(s)");
call add_other_drugs("Methotrexate 2.5mg","Methotrexate 2.5mg","Tablet(s)");
call add_other_drugs("Methotrexate 50mg/2ml","Methotrexate 50mg/2ml","Injection");
call add_other_drugs("Methyldopa 250mg","Methyldopa 250mg","Tablet(s)");
call add_other_drugs("Methylergometrine maleate 0.2mg/ml, 1ml","Methylergometrine maleate 0.2mg/ml, 1ml","For injection");
call add_other_drugs("Metoclopramide hcl 10mg","Metoclopramide hcl 10mg","Tablet(s)");
call add_other_drugs("Metoclopramide hcl 10mg/2ml","Metoclopramide hcl 10mg/2ml","Injection");
call add_other_drugs("Metronidazole 125mg/5ml","Metronidazole 125mg/5ml","Powder for oral suspension");
call add_other_drugs("Metronidazole 200mg","Metronidazole 200mg","Tablet(s)");
call add_other_drugs("Metronidazole 250mg","Metronidazole 250mg","Tablet(s)");
call add_other_drugs("Metronidazole 500mg","Metronidazole 500mg","Vaginal suppository");
call add_other_drugs("Metronidazole 5mg/ml, 100ml","Metronidazole 5mg/ml, 100ml","Injection");
call add_other_drugs("Miconazole 2% cream, 30g","Miconazole 2% cream, 30g","Cream");
call add_other_drugs("Morphine sulfate 10mg/ml, 1ml","Morphine sulfate 10mg/ml, 1ml","Injection");
call add_other_drugs("Multivitamin","Multivitamin","Tablet(s)");
call add_other_drugs("Nalidixic acid 500mg","Nalidixic acid 500mg","Tablet(s)");
call add_other_drugs("Naloxone 0.4mg/ml, 1ml","Naloxone 0.4mg/ml, 1ml","For injection");
call add_other_drugs("Neomycin 0.5% + bacitracin 500 iu/g","Neomycin 0.5% + bacitracin 500 iu/g","Ointment");
call add_other_drugs("Nevirapine (nvp) 100mg","Nevirapine (nvp) 100mg","Slow release tablet");
call add_other_drugs("Nevirapine (nvp) 200mg","Nevirapine (nvp) 200mg","Tablet(s)");
call add_other_drugs("Nevirapine (nvp) 400mg","Nevirapine (nvp) 400mg","Slow release tablet");
call add_other_drugs("Nevirapine (nvp) 50mg","Nevirapine (nvp) 50mg","Dispersable tablet");
call add_other_drugs("Nevirapine (nvp) 50mg/5ml","Nevirapine (nvp) 50mg/5ml","Oral suspension");
call add_other_drugs("Nifedipine 20mg","Nifedipine 20mg","Tablet(s)");
call add_other_drugs("Nitroglycerine 0.5mg (glyceryl trinitrate)","Nitroglycerine 0.5mg (glyceryl trinitrate)","Tablet(s)");
call add_other_drugs("Norethisterone 5mg","Norethisterone 5mg","Tablet(s)");
call add_other_drugs("Nystatin 100.000 iu","Nystatin 100.000 iu","Oral tablet");
call add_other_drugs("Nystatin 100.000 iu/g","Nystatin 100.000 iu/g","Ointment");
call add_other_drugs("Nystatin 100.000 iu/ml, 30ml","Nystatin 100.000 iu/ml, 30ml","Oral suspension");
call add_other_drugs("Nystatin 500.000 iu","Nystatin 500.000 iu","Oral tablet");
call add_other_drugs("Ombitasvir/paritaprevir/ritonavir  12.5mg/75mg/50mg","Ombitasvir/paritaprevir/ritonavir  12.5mg/75mg/50mg","Tablet(s)");
call add_other_drugs("Omeprazole 20mg","Omeprazole 20mg","Tablet(s)");
call add_other_drugs("Ondansetron 4mg","Ondansetron 4mg","Tablet(s)");
call add_other_drugs("Ondansetron 8mg","Ondansetron 8mg","Tablet(s)");
call add_other_drugs("Oral rehydration salts 20.5g/liter (low osmolarity) for 1 litre","Oral rehydration salts 20.5g/liter (low osmolarity) for 1 litre","Packet");
call add_other_drugs("Oral rehydration salts 27.9g/liter for 1 liter","Oral rehydration salts 27.9g/liter for 1 liter","Packet");
call add_other_drugs("Oxytocin 10 iu/ml, 1ml","Oxytocin 10 iu/ml, 1ml","Injection");
call add_other_drugs("Paracetamol 100mg","Paracetamol 100mg","Tablet(s)");
call add_other_drugs("Paracetamol 120mg, suppositories","Paracetamol 120mg, suppositories","Tablet(s)");
call add_other_drugs("Paracetamol 120mg/5ml, 5 liter","Paracetamol 120mg/5ml, 5 liter","Oral solution");
call add_other_drugs("Paracetamol 120mg/5ml, 60ml","Paracetamol 120mg/5ml, 60ml","Oral solution");
call add_other_drugs("Paracetamol 500mg","Paracetamol 500mg","Tablet(s)");
call add_other_drugs("Permethin 1% lotion, 100ml","Permethin 1% lotion, 100ml","Lotion");
call add_other_drugs("Phenobarbital 100mg","Phenobarbital 100mg","Tablet(s)");
call add_other_drugs("Phenobarbital 15mg","Phenobarbital 15mg","Tablet(s)");
call add_other_drugs("Phenobarbital 30mg","Phenobarbital 30mg","Tablet(s)");
call add_other_drugs("Phenobarbital 60mg","Phenobarbital 60mg","Tablet(s)");
call add_other_drugs("Phenoxymethylpenicillin 125mg/5ml, 100ml","Phenoxymethylpenicillin 125mg/5ml, 100ml","Powder for oral suspension");
call add_other_drugs("Phenoxymethylpenicillin 250mg","Phenoxymethylpenicillin 250mg","Tablet(s)");
call add_other_drugs("Phenytoin 100mg","Phenytoin 100mg","Tablet(s)");
call add_other_drugs("Phenytoin 250mg/5ml","Phenytoin 250mg/5ml","Injection");
call add_other_drugs("Pilocarpine hcl 2% eye drops, 5ml","Pilocarpine hcl 2% eye drops, 5ml","Eye drops");
call add_other_drugs("Potassium chloride 1 g/10ml","Potassium chloride 1 g/10ml","Injection");
call add_other_drugs("Potassium chloride 600mg","Potassium chloride 600mg","Slow release tablet");
call add_other_drugs("Praziquantel 600mg","Praziquantel 600mg","Tablet(s)");
call add_other_drugs("Prednisolone 5mg","Prednisolone 5mg","Tablet(s)");
call add_other_drugs("Primaquine 15mg","Primaquine 15mg","Base tablet");
call add_other_drugs("Procaine penicillin 1 miu","Procaine penicillin 1 miu","Powder for injection");
call add_other_drugs("Procaine penicillin 3 miu","Procaine penicillin 3 miu","Powder for injection");
call add_other_drugs("Procaine penicillin 3 miu / benzylpenicillin 1 miu","Procaine penicillin 3 miu / benzylpenicillin 1 miu","Powder for injection");
call add_other_drugs("Prochlorperazine 5 mg","Prochlorperazine 5 mg","Tablet(s)");
call add_other_drugs("Progesterone 25mg/ml, 1ml in oil","Progesterone 25mg/ml, 1ml in oil","Injection");
call add_other_drugs("Proguanil 100mg","Proguanil 100mg","Tablet(s)");
call add_other_drugs("Promethazine hcl 25mg","Promethazine hcl 25mg","Tablet(s)");
call add_other_drugs("Promethazine hcl 50mg/2ml","Promethazine hcl 50mg/2ml","Injection");
call add_other_drugs("Promethazine hcl 5mg/5ml oral solution, 100ml","Promethazine hcl 5mg/5ml oral solution, 100ml","Oral solution");
call add_other_drugs("Promethazine hcl 5mg/5ml oral solution, 5 liter","Promethazine hcl 5mg/5ml oral solution, 5 liter","Oral solution");
call add_other_drugs("Propranolol hcl 40mg","Propranolol hcl 40mg","Tablet(s)");
call add_other_drugs("Protamine sulphate 50mg/5ml","Protamine sulphate 50mg/5ml","Injection");
call add_other_drugs("Pvp iodine 10% ointment, 500g","Pvp iodine 10% ointment, 500g","Ointment");
call add_other_drugs("Pvp iodine 10% solution, 200ml","Pvp iodine 10% solution, 200ml","Solution");
call add_other_drugs("Pyrantel 250mg","Pyrantel 250mg","Tablet(s)");
call add_other_drugs("Quinine di-hcl 600mg/2ml","Quinine di-hcl 600mg/2ml","Injection");
call add_other_drugs("Quinine sulphate 200mg","Quinine sulphate 200mg","Tablet(s)");
call add_other_drugs("Quinine sulphate 300mg","Quinine sulphate 300mg","Tablet(s)");
call add_other_drugs("Rabies vaccine (vero cells) + solvent 0.5 ml","Rabies vaccine (vero cells) + solvent 0.5 ml","Powder + solvent");
call add_other_drugs("Raltegravir (ral) 100mg","Raltegravir (ral) 100mg","Powder for oral suspension");
call add_other_drugs("Raltegravir (ral) 25mg","Raltegravir (ral) 25mg","Soft tablet");
call add_other_drugs("Raltegravir (ral) 400mg","Raltegravir (ral) 400mg","Tablet(s)");
call add_other_drugs("Ranitidine 150mg","Ranitidine 150mg","Tablet(s)");
call add_other_drugs("Ribavirin 100 mg/ml","Ribavirin 100 mg/ml","Solution for nebulization");
call add_other_drugs("Ribavirin 200 mg","Ribavirin 200 mg","Capsule");
call add_other_drugs("Ribavirin 200mg/5ml","Ribavirin 200mg/5ml","Solution for nebulization");
call add_other_drugs("Ribavirin 400 mg","Ribavirin 400 mg","Tablet(s)");
call add_other_drugs("Ringer's lactate (hartmann's solution) 1000ml","Ringer's lactate (hartmann's solution) 1000ml","Bag for iv infusion");
call add_other_drugs("Ringer's lactate (hartmann's solution) 500ml","Ringer's lactate (hartmann's solution) 500ml","Bag for iv infusion");
call add_other_drugs("Risperidone 0.5mg","Risperidone 0.5mg","Tablet(s)");
call add_other_drugs("Risperidone 1mg","Risperidone 1mg","Tablet(s)");
call add_other_drugs("Risperidone 2mg","Risperidone 2mg","Tablet(s)");
call add_other_drugs("Ritonavir (rtv) 100mg","Ritonavir (rtv) 100mg","Soft tablet");
call add_other_drugs("Ritonavir (rtv) 50mg","Ritonavir (rtv) 50mg","Tablet(s)");
call add_other_drugs("Ritonavir (rtv) 80mg/ml","Ritonavir (rtv) 80mg/ml","Oral solution");
call add_other_drugs("Salbutamol  0.1 mg/dose (200 doses/inhaler)","Salbutamol  0.1 mg/dose (200 doses/inhaler)","Oral inhaler");
call add_other_drugs("Salbutamol 0.5mg/ml","Salbutamol 0.5mg/ml","Injection");
call add_other_drugs("Salbutamol 2mg tablet","Salbutamol 2mg tablet","Tablet(s)");
call add_other_drugs("Salbutamol 2mg/5ml","Salbutamol 2mg/5ml","Oral solution");
call add_other_drugs("Salbutamol 4mg","Salbutamol 4mg","Tablet(s)");
call add_other_drugs("Salbutamol respirator solution 5mg/ml","Salbutamol respirator solution 5mg/ml","Solution for nebulisation");
call add_other_drugs("Senna 7.5mg sennosides","Senna 7.5mg sennosides","Tablet(s)");
call add_other_drugs("Sertraline 25mg","Sertraline 25mg","Tablet(s)");
call add_other_drugs("Sertraline 50mg","Sertraline 50mg","Tablet(s)");
call add_other_drugs("Silver sulfadiazine 1%","Silver sulfadiazine 1%","Cream");
call add_other_drugs("Simeprevir 150mg","Simeprevir 150mg","Gel");
call add_other_drugs("Sodium bicarbonate 8.4%","Sodium bicarbonate 8.4%","Injection");
call add_other_drugs("Sodium chloride 0.9%, 1000ml","Sodium chloride 0.9%, 1000ml","Bag for iv infusion");
call add_other_drugs("Sodium chloride 0.9%, 500ml","Sodium chloride 0.9%, 500ml","Bag for iv infusion");
call add_other_drugs("Sofosbuvir, 400 mg","Sofosbuvir, 400 mg","Tablet(s)");
call add_other_drugs("Spironolactone 25mg","Spironolactone 25mg","Tablet(s)");
call add_other_drugs("Stavudine (d4t) 15mg","Stavudine (d4t) 15mg","Tablet(s)");
call add_other_drugs("Stavudine (d4t) 1mg/ml","Stavudine (d4t) 1mg/ml","Oral solution");
call add_other_drugs("Stavudine (d4t) 20mg","Stavudine (d4t) 20mg","Tablet(s)");
call add_other_drugs("Stavudine (d4t) 30mg","Stavudine (d4t) 30mg","Tablet(s)");
call add_other_drugs("Stavudine (d4t) 40mg","Stavudine (d4t) 40mg","Tablet(s)");
call add_other_drugs("Sulfadiazine 500mg","Sulfadiazine 500mg","Tablet(s)");
call add_other_drugs("Sulfadoxine 500mg + pyrimethamine 25mg","Sulfadoxine 500mg + pyrimethamine 25mg","Tablet(s)");
call add_other_drugs("Suxamethonium chloride 100mg/2ml","Suxamethonium chloride 100mg/2ml","Injection");
call add_other_drugs("Tenofovir (tdf) 150mg","Tenofovir (tdf) 150mg","Tablet(s)");
call add_other_drugs("Tenofovir (tdf) 200mg","Tenofovir (tdf) 200mg","Tablet(s)");
call add_other_drugs("Tenofovir (tdf) 245 mg","Tenofovir (tdf) 245 mg","Tablet(s)");
call add_other_drugs("Tenofovir (tdf) 250mg","Tenofovir (tdf) 250mg","Tablet(s)");
call add_other_drugs("Tenofovir (tdf) 300mg","Tenofovir (tdf) 300mg","Tablet(s)");
call add_other_drugs("Tenofovir (tdf) 40mg/1g","Tenofovir (tdf) 40mg/1g","Powder for oral suspension");
call add_other_drugs("Tenofovir/emtricitabine/efavirenz (tdf/ftc/efv) 300mg/200mg/600mg","Tenofovir/emtricitabine/efavirenz (tdf/ftc/efv) 300mg/200mg/600mg","Tablet(s)");
call add_other_drugs("Tenofovir/fumarate (tdf/ftc) 300mg/200mg","Tenofovir/fumarate (tdf/ftc) 300mg/200mg","Tablet(s)");
call add_other_drugs("Tenofovir/lamivudine (tdf/3tc) 300mg/300mg","Tenofovir/lamivudine (tdf/3tc) 300mg/300mg","Tablet(s)");
call add_other_drugs("Tenofovir/lamivudine/efavirenz (tdf/3tc/efv) 300mg/300mg/600mg","Tenofovir/lamivudine/efavirenz (tdf/3tc/efv) 300mg/300mg/600mg","Tablet(s)");
call add_other_drugs("Tetanus antitoxin 1.500 iu, 1ml","Tetanus antitoxin 1.500 iu, 1ml","Injection");
call add_other_drugs("Tetanus vaccine 20doses/vial (tetanus toxoid)","Tetanus vaccine 20doses/vial (tetanus toxoid)","Injection");
call add_other_drugs("Tetracaine hcl 0.5% eye drops, 10ml (amethocaine)","Tetracaine hcl 0.5% eye drops, 10ml (amethocaine)","Eye drops");
call add_other_drugs("Tetracycline hcl 1% eye ointment, 5g","Tetracycline hcl 1% eye ointment, 5g","Eye ointment");
call add_other_drugs("Tetracycline hcl 3% skin ointment, 15g","Tetracycline hcl 3% skin ointment, 15g","Skin ointment");
call add_other_drugs("Thiopental sodium 1g","Thiopental sodium 1g","Powder for injection");
call add_other_drugs("Thiopental sodium, 500mg","Thiopental sodium, 500mg","Powder for injection");
call add_other_drugs("Timolol 0.25% eye-drops, 5ml","Timolol 0.25% eye-drops, 5ml","Eye drops");
call add_other_drugs("Timolol 0.5 % eye drops, 5ml","Timolol 0.5 % eye drops, 5ml","Eye drops");
call add_other_drugs("Tinidazole 500mg","Tinidazole 500mg","Tablet(s)");
call add_other_drugs("Tramadol hcl 100mg/2ml","Tramadol hcl 100mg/2ml","Injection");
call add_other_drugs("Tropicamide 0.5% eye drops, 5ml","Tropicamide 0.5% eye drops, 5ml","Eye drops");
call add_other_drugs("Valproic acid 150mg","Valproic acid 150mg","Tablet(s)");
call add_other_drugs("Verapamil hcl 40mg","Verapamil hcl 40mg","Tablet(s)");
call add_other_drugs("Vitamin a  50.000 iu (retinol)","Vitamin a  50.000 iu (retinol)","Tablet(s)");
call add_other_drugs("Vitamin a 100.000 iu (retinol)","Vitamin a 100.000 iu (retinol)","Tablet(s)");
call add_other_drugs("Vitamin a 200.000 iu (retinol)","Vitamin a 200.000 iu (retinol)","Tablet(s)");
call add_other_drugs("Vitamin b1  100mg/2ml (thiamine hcl)","Vitamin b1  100mg/2ml (thiamine hcl)","Injection");
call add_other_drugs("Vitamin b12  1mg/ml (cyanocobalamine)","Vitamin b12  1mg/ml (cyanocobalamine)","Injection");
call add_other_drugs("Vitamin b6  100mg/2ml (pyridoxine hcl)","Vitamin b6  100mg/2ml (pyridoxine hcl)","Injection");
call add_other_drugs("Vitamin b6  25mg (pyridoxine hcl)","Vitamin b6  25mg (pyridoxine hcl)","Tablet(s)");
call add_other_drugs("Vitamin b6  50mg (pyridoxine hcl)","Vitamin b6  50mg (pyridoxine hcl)","Tablet(s)");
call add_other_drugs("Vitamin c 250mg (ascorbic acid)","Vitamin c 250mg (ascorbic acid)","Tablet(s)");
call add_other_drugs("Vitamin k1 1mg/ml (phytomenadione)","Vitamin k1 1mg/ml (phytomenadione)","Injection");
call add_other_drugs("Warfarin sodium 5mg","Warfarin sodium 5mg","Tablet(s)");
call add_other_drugs("Water for injection, 10ml","Water for injection, 10ml","Injection");
call add_other_drugs("Water for injection, 5ml","Water for injection, 5ml","Injection");
call add_other_drugs("Zidovudine (azt) 100mg","Zidovudine (azt) 100mg","Tablet(s)");
call add_other_drugs("Zidovudine (azt) 200mg/20ml, for injection","Zidovudine (azt) 200mg/20ml, for injection","Injection ");
call add_other_drugs("Zidovudine (azt) 300 mg","Zidovudine (azt) 300 mg","Tablet(s)");
call add_other_drugs("Zidovudine (azt) 50mg/5ml oral solution, 100ml","Zidovudine (azt) 50mg/5ml oral solution, 100ml","Oral solution");
call add_other_drugs("Zidovudine (azt) 50mg/5ml oral solution, 200ml","Zidovudine (azt) 50mg/5ml oral solution, 200ml","Oral solution");
call add_other_drugs("Zidovudine (azt) 50mg/5ml oral solution, 240ml","Zidovudine (azt) 50mg/5ml oral solution, 240ml","Oral solution");
call add_other_drugs("Zidovudine/lamivudine/nevirapine (azt/3tc/nvp) 60 mg/30 mg/50 mg","Zidovudine/lamivudine/nevirapine (azt/3tc/nvp) 60 mg/30 mg/50 mg","Tablet(s)");
call add_other_drugs("Zinc dispersable tablet 20mg (as zinc sulphate)","Zinc dispersable tablet 20mg (as zinc sulphate)","Tablet(s)");
call add_other_drugs("Zinc oxide ointment 10%","Zinc oxide ointment 10%","Ointment");