INSERT INTO concept VALUES
(NULL,0,"acetazolamide 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"acetylsalicylic acid 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"acetylsalicylic acid 300mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"acetylsalicylic acid 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"aciclovir 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"aciclovir 3% eye ointment, 4.5g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"aciclovir 5% cream, 2g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"albendazole 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"albendazole 400mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"albuterol oral inhaler, 90mcg/dose, 200 doses",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"albuterol 0.5ml solution of 5% (2.5mg) for nebulization",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"allopurinol 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"aluminium hydroxide 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"amiloride 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"aminophylline 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"aminophylline 250mg/10ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"amitriptyline HCl 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"amodiaquine HCl, equivalent to 200mg base tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"amoxicillin 125mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"amoxicillin 250mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"amoxicillin 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"amoxicillin 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"amoxicillin 500mg + clavulanic acid 125mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"amphotericin b, 50mg dry powder for injection (10ml)   ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ampicillin 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ampicillin 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ampicillin 500mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ampicillin 1 gram, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"antacida suspension (aluminium+magnesiumhydroxide), 300ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"anti-haemorrhoid ointment, 30g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"anti-haemorrhoid suppositories (tablet)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"anti-rabies immunoglobuline, human 300iu/2ml, for injection ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"anti-snake bite serum, Africa (10 snakes), 10ml for injection ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"artemether 20mg + lumefantrine 120mg (Coartem) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"artemether 20mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"artemether 80mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"artesunate 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"artesunate 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"artesunate 50mg + amodiaquine 153mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"atenolol 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"atenolol 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"atropine sulphate 1% eye drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"atropine sulphate 1mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"azathioprine 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"azithromycine 200mg/5ml, oral suspension,15ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"azithromycine 250 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"beclometasone oral inhaler, 50mcg/dose, 200 doses",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"benzathine penicillin 1.2 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"benzathine penicillin 2.4 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"benzoic acid 6% + salicylic acid 3% ointment, 40g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"benzoic acid 6% + salicylic acid 3% ointment, 800g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"benzotropine 1mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"benzylbenzoate 25% application, 1 liter",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"benzylbenzoate 90% saponated, 1 liter",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"benzylpenicillin 1 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"benzylpenicillin 5 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"betamethasone 0.1% (as valerate) cream, 15g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"biperiden HCl 2mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"bisacodyl 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"bleomycin powder, 15.000 IU",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"bupivacaine 0.5%, 20ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"bupivacaine spinal heavy 0.5%, 4ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"calamine lotion, 500ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"calcium gluconate 1g/10ml (2.23mmol), for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"calcium lactate 300mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"captopril 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"carbamazepine 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"carbimazole 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"carbon absorbent 125mg bottle",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"cefalexin 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"cefixime 200 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"cefixime 400 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ceftriaxone 250mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ceftriaxone 500mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ceftriaxon 1g, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chloramphenicol 125mg/5ml oral suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chloramphenicol 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chloramphenicol 500mg/2ml in oil, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chloramphenicol 1 g (as sodium succinate), for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chloramphenicol 10% ear drops, 10ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chloramphenicol 0.5% eye drops 10ml ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chloramphenicol 1% eye ointment, 5g tubes",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chloroquine phosphate 10mg base/ml, oral solution, 60ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chloroquine phosphate 100mg base tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chloroquine phosphate 150mg base tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chloroquine phosphate 200mg base/5ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chlorphenamine maleate 4mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chlorphenamine maleate 10mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chlorpromazine HCl 25mg, tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chlorpromazine HCl 100mg, tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"chlorpromazine HCl 50mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"cimetidine 200mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"cimetidine 200mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ciprofloxacin 250mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ciprofloxacin 500mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"clotrimazole 1% cream, 20g tubes",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"clotrimazole vaginal 500mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"cloxacillin 125mg/5ml, powder for oral solution, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"cloxacillin 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"cloxacillin 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"codeine phosphate 30mg  tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"co-trimoxazole 100mg+20mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"co-trimoxazole 400mg+80mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"co-trimoxazole 800mg+160mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"co-trimoxazole 200mg+40mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"dapsone 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"dexamethasone 0.5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"dexamethasone sodium phosphate 5mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"dexamethasone 1mg/ml (as sodium phosphate), eye drops, 10ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"dextrose 2.5% in NaCl 0.45%, 1000ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"dextrose 5% in water, 500ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"dextrose 5% in water, 1000ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"dextrose 10% in water, 500ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"dextrose 50%, 50ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"diazepam 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"diazepam 10mg/2ml, for injection  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"diclofenac sodium 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"diclofenac sodium 75mg/3ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"diphenhydramine 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"digoxine 0.25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"digoxine 0.5mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"dimenhydrinate 50 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"dopamine HCl 200mg/5ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"doxycycline 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ephedrine HCl 30mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"epinephrine 1mg/ml, 1ml (adrenaline), for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ergometrine maleate 0.5mg/ml, 1ml, for injection  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ergotamine 1mg + caffeine 100 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"erythromycin 125mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"erythromycin 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ethinylestradiol/levonorgestrel 0.03/0.15mg, 28 tablet blister",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"fentanyl 0.1mg/2ml, for injection   ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ferrous fumarate 100mg/5ml oral suspension, 5 liter",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ferrous sulphate 200mg + folic acid 0.25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ferrous sulphate 200mg + folic acid 0.4mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ferrous sulphate 200mg, coated tablet (65mg iron)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"fluconazole 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"fluconazole 150mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"fluconazole 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"fluoxetine 20mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"folic acid 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"furosemide 40mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"furosemide 20mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ganciclovir 500 mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"gentamicin 20mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"gentamicin 80mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"gentamicin 0.3% eye drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"glibenclamide 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"griseofulvin 125mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"griseofulvin 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"haloperidol 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"haloperidol 5mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"heparine sodium 5000 iu/ml, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"hydralazine HCl 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"hydralazine 20mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"hydrochlorothiazide 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"hydrochlorothiazide 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"hydrocortisone 100mg (as sodium succinate), powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"hydrocortisone acetate 1% eye ointment, 5g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"hydrocortisone acetate 1% skin ointment, 15g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"hydrocortisone acetate 1% cream, 15g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"hyoscine butylbromide 10mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"hyoscine butylbromide 20mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ibuprofen 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ibuprofen 400mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"indometacin 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"iron dextran 100mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"isosorbide dinitrate 5mg, sublingual",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ketamine 50mg/ml, 10ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ketoconazole 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"levodopa 250mg + carbidopa 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"levonorgestrel 0.75mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"levothyroxine sodium 0.1mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"lidocaine HCl 1%, 20ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"lidocaine HCl 2%, 20ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"lidocaine HCl 5% + dextrose 7.5%, 2ml, for injection (spinal)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"lidocaine HCl 2% + epinephrine dental, 1.8ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"lidocaine HCl 2% jelly, 30ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"lisinopril 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"lisinopril 10mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"loperamide HCl 2mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"lorazepam 0.5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"lorazepam 1mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"magnesium sulphate 50%, 20ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"magnesium trisilicate compound 250/120 mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"mannitol 20% solution, 500ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"meclazine 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"mebendazole 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"mebendazole 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"mebendazole 100mg/5ml oral suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"medroxyprogesteronacetate 150mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"mefloquine 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"metformine HCl 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"methotrexate 2.5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"methotrexate 50mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"methyldopa 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"methylergometrine maleate 0.2mg/ml, 1ml, for injection  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"metoclopramide HCl 10mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"metoclopramide HCl 10mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"metronidazole 125mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"metronidazole 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"metronidazole 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"metronidazole 5mg/ml, 100ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"metronidazole 500mg vaginal suppository",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"miconazole 10mg muco-adhesive buccal tabs, blister",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"miconazole 2% cream, 30g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"morphine sulfate 10mg/ml, 1ml, for injection  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"multivitamin tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"nalidixic acid 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"naloxone 0.4mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"neomycin 0.5% + bacitracin 500 iu/g ointment, 15g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"nifedipine 20mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"nitroglycerine 0.5mg (glyceryl trinitrate) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"norethisterone 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"nystatin 100.000 iu/ml oral suspension, 30ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"nystatin 100.000 iu oral tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"nystatin 500.000 iu oral tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"nystatin ointment 100.000 iu/g, 30g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"nystatin 100.000 iu vaginal suppository",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"odansetron 4mg tablets",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"odansetron 8mg tablets",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Oral Rehydration Salts 27.9g/liter ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Oral Rehydration Salts 20.5g/liter (low osmolarity)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"omeprazole 20mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"oxytocin 10 iu/ml, 1ml, for injection  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"paracetamol 120mg/5ml oral solution, 60ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"paracetamol 120mg/5ml oral solution, 5 liter",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"paracetamol 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"paracetamol 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"paracetamol 120mg, suppositories  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"permethin 1% lotion, 100ml ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"phenobarbital 15mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"phenobarbital 30mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"phenobarbital 60mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"phenobarbital 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"phenoxymethylpenicillin 125mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"phenoxymethylpenicillin 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"phenytoin 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"phenytoin 250mg/5ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"pilocarpine HCl 2% eye drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"potassium chloride 600mg, slow release tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"potassium chloride 1 g/10ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"praziquantel 600mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"prednisolone 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"primaquine 15mg base tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"procaine penicillin 1 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"procaine penicillin 3 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"procaine penicillin 3 miu / benzylpenicillin 1 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"prochlorperazine 5 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"progesterone 25mg/ml, 1ml in oil, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"proguanil 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"promethazine HCl 5mg/5ml oral solution, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"promethazine HCl 5mg/5ml oral solution, 5 liter",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"promethazine HCl 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"promethazine HCl 50mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"propranolol HCl 40mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"protamine sulphate 50mg/5ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"pvp iodine 10% ointment, 500g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"pvp iodine 10% solution, 200ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"pyrantel 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"quinine sulphate 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"quinine sulphate 300mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"quinine di-HCl 600mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"rabies vaccine (vero cells) + solvent 0.5 ml   ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"ranitidine 150mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"risperidone 0.5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"risperidone 1mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"risperidone 2mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ringer's lactate (Hartmann's solution), 500ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ringer's lactate (Hartmann's solution), 1000ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"salbutamol 2mg/5ml, oral solution, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"salbutamol 2mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"salbutamol 4mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"salbutamol 0.5mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"salbutamol oral inhaler, 0.1 mg/dose, 200 doses  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"salbutamol respirator solution 5mg/ml, 30ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"senna 7.5mg sennosides",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"silver sulfadiazine 1% cream, 50g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"sodium bicarbonate 8.4%, 20ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"sodium chloride 0.9%, 500ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"sodium chloride 0.9%, 1000ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"spironolactone 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"sertraline 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"sertraline 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"sulfadiazine 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"sulfadoxine 500mg + pyrimethamine 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"suxamethonium chloride 100mg/2ml, for injection    ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"tetanus antitoxin 1.500 iu, 1ml, for injection   ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"tetanus vaccine 20doses/vial (tetanus toxoid)  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"tetracaine HCl 0.5% eye drops, 10ml (amethocaine)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"tetracycline HCl 1% eye ointment, 5g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"tetracycline HCl 3% skin ointment, 15g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"thiopental sodium, 500mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"thiopental sodium 1g, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"timolol 0.25% eye-drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"timolol 0.5 % eye drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"tinidazole 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"tramadol HCl 100mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"tropicamide 0.5% eye drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"valproic acid 150mg, enteric coated",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"verapamil HCl 40mg, coated",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"vitamin A  50.000 iu (retinol) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"vitamin A 100.000 IU (retinol) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"vitamin A 200.000 iu (retinol) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"vitamin B1  100mg/2ml, for injection (thiamine HCl)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"vitamin B6  25mg (pyridoxine HCl) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"vitamin B6  50mg (pyridoxine HCl) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"vitamin B6  100mg/2ml, for injection (pyridoxine HCl) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"vitamin B12  1mg/ml, 1ml, for injection (cyanocobalamine)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"vitamin C 250mg (ascorbic acid)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"vitamin K1 1mg/ml, 1ml, for injection (phytomenadione)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"warfarin sodium 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"water for injection, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"water for injection, 10ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"zinc dispersable tablet 20mg (as zinc sulphate) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"zinc oxide ointment 10%, 100g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"zinc oxide ointment 10%, 800g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid());
