INSERT INTO concept VALUES
(NULL,0,"Acetazolamide 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Acetylsalicylic acid 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Acetylsalicylic acid 300mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Acetylsalicylic acid 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Aciclovir 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Aciclovir 3% eye ointment, 4.5g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Aciclovir 5% cream, 2g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Albendazole 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Albendazole 400mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Albuterol oral inhaler, 90mcg/dose, 200 doses",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Albuterol 0.5ml solution of 5% (2.5mg) for nebulization",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Allopurinol 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Aluminium hydroxide 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Amiloride 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Aminophylline 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Aminophylline 250mg/10ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Amitriptyline HCl 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Amodiaquine HCl, equivalent to 200mg base tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Amoxicillin 125mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Amoxicillin 250mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Amoxicillin 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Amoxicillin 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Amoxicillin 500mg + clavulanic acid 125mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Amphotericin b, 50mg dry powder for injection (10ml)   ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ampicillin 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ampicillin 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ampicillin 500mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ampicillin 1 gram, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Antacida suspension (aluminium+magnesiumhydroxide), 300ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Anti-haemorrhoid ointment, 30g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Anti-haemorrhoid suppositories (tablet)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Anti-rabies immunoglobuline, human 300iu/2ml, for injection ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Anti-snake bite serum, Africa (10 snakes), 10ml for injection ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Artemether 20mg + lumefantrine 120mg (Coartem) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Artemether 20mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Artemether 80mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Artesunate 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Artesunate 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Artesunate 50mg + amodiaquine 153mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Atenolol 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Atenolol 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Atropine sulphate 1% eye drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Atropine sulphate 1mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Azathioprine 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Azithromycine 200mg/5ml, oral suspension,15ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Azithromycine 250 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Beclometasone oral inhaler, 50mcg/dose, 200 doses",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Benzathine penicillin 1.2 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Benzathine penicillin 2.4 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Benzoic acid 6% + salicylic acid 3% ointment, 40g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Benzoic acid 6% + salicylic acid 3% ointment, 800g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Benzotropine 1mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Benzylbenzoate 25% application, 1 liter",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Benzylbenzoate 90% saponated, 1 liter",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Benzylpenicillin 1 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Benzylpenicillin 5 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Betamethasone 0.1% (as valerate) cream, 15g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Biperiden HCl 2mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Bisacodyl 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Bleomycin powder, 15.000 IU",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Bupivacaine 0.5%, 20ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Bupivacaine spinal heavy 0.5%, 4ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Calamine lotion, 500ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Calcium gluconate 1g/10ml (2.23mmol), for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Calcium lactate 300mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Captopril 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Carbamazepine 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Carbimazole 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Carbon absorbent 125mg bottle",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Cefalexin 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Cefixime 200 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Cefixime 400 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ceftriaxone 250mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ceftriaxone 500mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ceftriaxon 1g, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chloramphenicol 125mg/5ml oral suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chloramphenicol 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chloramphenicol 500mg/2ml in oil, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chloramphenicol 1 g (as sodium succinate), for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chloramphenicol 10% ear drops, 10ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chloramphenicol 0.5% eye drops 10ml ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chloramphenicol 1% eye ointment, 5g tubes",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chloroquine phosphate 10mg base/ml, oral solution, 60ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chloroquine phosphate 100mg base tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chloroquine phosphate 150mg base tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chloroquine phosphate 200mg base/5ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chlorphenamine maleate 4mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chlorphenamine maleate 10mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chlorpromazine HCl 25mg, tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chlorpromazine HCl 100mg, tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Chlorpromazine HCl 50mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Cimetidine 200mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Cimetidine 200mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ciprofloxacin 250mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ciprofloxacin 500mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Clotrimazole 1% cream, 20g tubes",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Clotrimazole vaginal 500mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Cloxacillin 125mg/5ml, powder for oral solution, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Cloxacillin 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Cloxacillin 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Codeine phosphate 30mg  tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Co-trimoxazole 100mg+20mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Co-trimoxazole 400mg+80mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Co-trimoxazole 800mg+160mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Co-trimoxazole 200mg+40mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Dapsone 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Dexamethasone 0.5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Dexamethasone sodium phosphate 5mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Dexamethasone 1mg/ml (as sodium phosphate), eye drops, 10ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Dextrose 2.5% in NaCl 0.45%, 1000ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Dextrose 5% in water, 500ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Dextrose 5% in water, 1000ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Dextrose 10% in water, 500ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Dextrose 50%, 50ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Diazepam 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Diazepam 10mg/2ml, for injection  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Diclofenac sodium 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Diclofenac sodium 75mg/3ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Diphenhydramine 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Digoxine 0.25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Digoxine 0.5mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Dimenhydrinate 50 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Dopamine HCl 200mg/5ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Doxycycline 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ephedrine HCl 30mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Epinephrine 1mg/ml, 1ml (adrenaline), for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ergometrine maleate 0.5mg/ml, 1ml, for injection  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ergotamine 1mg + caffeine 100 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Erythromycin 125mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Erythromycin 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ethinylestradiol/levonorgestrel 0.03/0.15mg, 28 tablet blister",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Fentanyl 0.1mg/2ml, for injection   ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ferrous fumarate 100mg/5ml oral suspension, 5 liter",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ferrous sulphate 200mg + folic acid 0.25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ferrous sulphate 200mg + folic acid 0.4mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ferrous sulphate 200mg, coated tablet (65mg iron)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Fluconazole 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Fluconazole 150mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Fluconazole 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Fluoxetine 20mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Folic acid 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Furosemide 40mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Furosemide 20mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ganciclovir 500 mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Gentamicin 20mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Gentamicin 80mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Gentamicin 0.3% eye drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Glibenclamide 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Griseofulvin 125mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Griseofulvin 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Haloperidol 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Haloperidol 5mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Heparine sodium 5000 iu/ml, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Hydralazine HCl 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Hydralazine 20mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Hydrochlorothiazide 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Hydrochlorothiazide 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Hydrocortisone 100mg (as sodium succinate), powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Hydrocortisone acetate 1% eye ointment, 5g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Hydrocortisone acetate 1% skin ointment, 15g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Hydrocortisone acetate 1% cream, 15g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Hyoscine butylbromide 10mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Hyoscine butylbromide 20mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ibuprofen 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ibuprofen 400mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Indometacin 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Iron dextran 100mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Isosorbide dinitrate 5mg, sublingual",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ketamine 50mg/ml, 10ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ketoconazole 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Levodopa 250mg + carbidopa 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Levonorgestrel 0.75mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Levothyroxine sodium 0.1mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Lidocaine HCl 1%, 20ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Lidocaine HCl 2%, 20ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Lidocaine HCl 5% + dextrose 7.5%, 2ml, for injection (spinal)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Lidocaine HCl 2% + epinephrine dental, 1.8ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Lidocaine HCl 2% jelly, 30ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Lisinopril 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Lisinopril 10mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Loperamide HCl 2mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Lorazepam 0.5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Lorazepam 1mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Magnesium sulphate 50%, 20ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Magnesium trisilicate compound 250/120 mg",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Mannitol 20% solution, 500ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Meclazine 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Mebendazole 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Mebendazole 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Mebendazole 100mg/5ml oral suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Medroxyprogesteronacetate 150mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Mefloquine 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Metformine HCl 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Methotrexate 2.5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Methotrexate 50mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Methyldopa 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Methylergometrine maleate 0.2mg/ml, 1ml, for injection  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Metoclopramide HCl 10mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Metoclopramide HCl 10mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Metronidazole 125mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Metronidazole 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Metronidazole 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Metronidazole 5mg/ml, 100ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Metronidazole 500mg vaginal suppository",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Miconazole 10mg muco-adhesive buccal tabs, blister",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Miconazole 2% cream, 30g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Morphine sulfate 10mg/ml, 1ml, for injection  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Multivitamin tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Nalidixic acid 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Naloxone 0.4mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Neomycin 0.5% + bacitracin 500 iu/g ointment, 15g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Nifedipine 20mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Nitroglycerine 0.5mg (glyceryl trinitrate) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Norethisterone 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Nystatin 100.000 iu/ml oral suspension, 30ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Nystatin 100.000 iu oral tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Nystatin 500.000 iu oral tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Nystatin ointment 100.000 iu/g, 30g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Nystatin 100.000 iu vaginal suppository",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Odansetron 4mg tablets",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Odansetron 8mg tablets",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Oral Rehydration Salts 27.9g/liter ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Oral Rehydration Salts 20.5g/liter (low osmolarity)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Omeprazole 20mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Oxytocin 10 iu/ml, 1ml, for injection  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Paracetamol 120mg/5ml oral solution, 60ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Paracetamol 120mg/5ml oral solution, 5 liter",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Paracetamol 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Paracetamol 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Paracetamol 120mg, suppositories  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Permethin 1% lotion, 100ml ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Phenobarbital 15mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Phenobarbital 30mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Phenobarbital 60mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Phenobarbital 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Phenoxymethylpenicillin 125mg/5ml, powder for suspension, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Phenoxymethylpenicillin 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Phenytoin 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Phenytoin 250mg/5ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Pilocarpine HCl 2% eye drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Potassium chloride 600mg, slow release tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Potassium chloride 1 g/10ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Praziquantel 600mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Prednisolone 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Primaquine 15mg base tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Procaine penicillin 1 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Procaine penicillin 3 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Procaine penicillin 3 miu / benzylpenicillin 1 miu, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Prochlorperazine 5 mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Progesterone 25mg/ml, 1ml in oil, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Proguanil 100mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Promethazine HCl 5mg/5ml oral solution, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Promethazine HCl 5mg/5ml oral solution, 5 liter",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Promethazine HCl 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Promethazine HCl 50mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Propranolol HCl 40mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Protamine sulphate 50mg/5ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Pvp iodine 10% ointment, 500g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Pvp iodine 10% solution, 200ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Pyrantel 250mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Quinine sulphate 200mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Quinine sulphate 300mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Quinine di-HCl 600mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Rabies vaccine (vero cells) + solvent 0.5 ml   ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ranitidine 150mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Risperidone 0.5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Risperidone 1mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Risperidone 2mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ringer's lactate (Hartmann's solution), 500ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Ringer's lactate (Hartmann's solution), 1000ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Salbutamol 2mg/5ml, oral solution, 100ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Salbutamol 2mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Salbutamol 4mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Salbutamol 0.5mg/ml, 1ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Salbutamol oral inhaler, 0.1 mg/dose, 200 doses  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Salbutamol respirator solution 5mg/ml, 30ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Senna 7.5mg sennosides",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Silver sulfadiazine 1% cream, 50g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Sodium bicarbonate 8.4%, 20ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Sodium chloride 0.9%, 500ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Sodium chloride 0.9%, 1000ml bag for IV infusion",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Spironolactone 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Sertraline 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Sertraline 50mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Sulfadiazine 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Sulfadoxine 500mg + pyrimethamine 25mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Suxamethonium chloride 100mg/2ml, for injection    ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Tetanus antitoxin 1.500 iu, 1ml, for injection   ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Tetanus vaccine 20doses/vial (tetanus toxoid)  ",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Tetracaine HCl 0.5% eye drops, 10ml (amethocaine)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Tetracycline HCl 1% eye ointment, 5g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Tetracycline HCl 3% skin ointment, 15g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Thiopental sodium, 500mg, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Thiopental sodium 1g, powder for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Timolol 0.25% eye-drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Timolol 0.5 % eye drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Tinidazole 500mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Tramadol HCl 100mg/2ml, for injection",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Tropicamide 0.5% eye drops, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Valproic acid 150mg, enteric coated",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Verapamil HCl 40mg, coated",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Vitamin A  50.000 iu (retinol) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Vitamin A 100.000 IU (retinol) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Vitamin A 200.000 iu (retinol) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Vitamin B1  100mg/2ml, for injection (thiamine HCl)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Vitamin B6  25mg (pyridoxine HCl) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Vitamin B6  50mg (pyridoxine HCl) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Vitamin B6  100mg/2ml, for injection (pyridoxine HCl) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Vitamin B12  1mg/ml, 1ml, for injection (cyanocobalamine)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Vitamin C 250mg (ascorbic acid)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Vitamin K1 1mg/ml, 1ml, for injection (phytomenadione)",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Warfarin sodium 5mg tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Water for injection, 5ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Water for injection, 10ml",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Zinc dispersable tablet 20mg (as zinc sulphate) tablet",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Zinc oxide ointment 10%, 100g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid()),
(NULL,0,"Zinc oxide ointment 10%, 800g",NULL,NULL,4,3,0,4,now(),NULL,4,now(),NULL,NULL,NULL,uuid());
